### ISSUE TITLE
rbenv-vars and BUNDLE_GEMFILE

### ISSUE THREAD

**Issue by PaBLoX-CL** [sstephenson/rbenv-vars#23]
I was trying to use `.rbenv-vars` to be able to access an alternate gemfile (mostly using local gems and formatters), and while works fine while being in the "project root", it doesn't when changing to a "deeper" directory.

This happens because `BUNDLE_GEMFILE` is set to `Gemfile.local`, but when trying to run `bundle exec bin`, it tries to load the local gemfile for the working directory (and of course it doesn't exists, since `Gemfile`s only exists in the root).

To workaround this, I'm "hard-coding" the full path so the `BUNDLE_GEMFILE` variable contains always the full path:

```
# .rbenv-vars
PROJ_DIR=~/code/full/path/to/project
BUNDLE_GEMFILE?=$PROJ_DIR/Gemfile.local
```

Initially I naively tried to use `$PWD/Gemfile.local`, but it actually expands to the working directory, resulting in an error not being able to found the file.

I can't think any way to fix this :/, any idea?

**Comment by mislav** [comment]
No idea how to fix this either. Maybe we could export something like `RBENV_VARS_ROOT` which would reflect the current path where this `.rbenv-vars` was read. It's a long-shot, though. Right now this information is not available.

You could also make your own rbenv plugin to cover this.

**Comment by PaBLoX-CL** [comment]
Yes, it's too much work. I guess I'll stay with the workaround in the meantime :P
