### ISSUE TITLE
How to use for multiple apps.

### ISSUE THREAD

**Issue by dflourusso** [sstephenson/rbenv-vars#26]
I have two apps in the same server deployed with capistrano.
I put the *.env-vars.app1* and *.env-vars.app1* in my user home folder.
Each app has different values for the variable.
How to configure it?

**Comment by mislav** [comment]
Make a separate `.rbenv-vars` file in the root directory of each project. Put different configuration in those files. That configuration will only be loaded in that project directory (and all subdirectories).

**Comment by dflourusso** [comment]
Ok, thanks.
